DROP DATABASE IF EXISTS speakUp_db;
CREATE DATABASE speakUp_db;
USE speakUp_db;

CREATE TABLE users (
  userID INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL,
  admin BOOLEAN NOT NULL,
  dateJoined DATETIME,
  postNumber INTEGER(10),
  PRIMARY KEY (userID)
);

CREATE TABLE forums (
  forumID INTEGER NOT NULL AUTO_INCREMENT,
  title VARCHAR(50) NOT NULL,
  description TEXT,
  userID INTEGER NOT NULL,
  dateCreated DATETIME,
  PRIMARY KEY (forumID),
  FOREIGN KEY (userID) REFERENCES users(userID)
);

CREATE TABLE posts (
  postID INTEGER NOT NULL AUTO_INCREMENT,
  forumID INTEGER NOT NULL,
  subject VARCHAR(100) NOT NULL,
  content MEDIUMTEXT,
  userID INTEGER NOT NULL,
  datePosted DATETIME,
  PRIMARY KEY (postID),
  FOREIGN KEY (forumID) REFERENCES forums(forumID),
  FOREIGN KEY (userID) REFERENCES users(userID)
)