DROP DATABASE IF EXISTS speakUp_db;
CREATE DATABASE speakUp_db;
USE speakUp_db;

CREATE TABLE users (
  userID INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL,
  email VARCHAR(50) NOT NULL,
  dateJoined DATETIME,
  postNumber INTEGER(10),
  PRIMARY KEY (userID)
);

CREATE TABLE topics (
  topicID INTEGER NOT NULL AUTO_INCREMENT,
  subject VARCHAR(50) NOT NULL,
  category VARCHAR(30) NOT NULL,
  content TEXT,
  userID INTEGER NOT NULL,
  datePosted DATETIME,
  PRIMARY KEY (topicID),
  FOREIGN KEY (userID) REFERENCES users(userID)
);

CREATE TABLE replies (
  replyID INTEGER NOT NULL AUTO_INCREMENT,
  topicID INTEGER NOT NULL,
  repliedID INTEGER,
  subject VARCHAR(100) NOT NULL,
  content MEDIUMTEXT,
  userID INTEGER NOT NULL,
  datePosted DATETIME,
  PRIMARY KEY (postID),
  FOREIGN KEY (topicID) REFERENCES topics(topicID),
  FOREIGN KEY (userID) REFERENCES users(userID)
)