DROP DATABASE IF EXISTS speakUp_db;
CREATE DATABASE speakUp_db;
USE speakUp_db;

CREATE TABLE users (
  userID INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL,
  email VARCHAR(50) NOT NULL,
  dateJoined DATETIME,
  postNumber INTEGER NOT NULL DEFAULT(0),
  PRIMARY KEY (userID)
);

CREATE TABLE topics (
  topicID INTEGER NOT NULL AUTO_INCREMENT,
  subject VARCHAR(50) NOT NULL,
  category VARCHAR(30) NOT NULL,
  content TEXT,
  userID INTEGER NOT NULL,
  datePosted DATETIME,
  edited BOOLEAN NOT NULL DEFAULT(0),
  lastEdited DATETIME,
  PRIMARY KEY (topicID),
  FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
);

CREATE TABLE replies (
  replyID INTEGER NOT NULL AUTO_INCREMENT,
  topicID INTEGER NOT NULL,
  repliedID INTEGER,
  subject VARCHAR(100) NOT NULL,
  content MEDIUMTEXT,
  userID INTEGER NOT NULL,
  datePosted DATETIME,
  edited BOOLEAN NOT NULL DEFAULT(0),
  lastEdited DATETIME,
  PRIMARY KEY (replyID),
  FOREIGN KEY (topicID) REFERENCES topics(topicID) ON DELETE CASCADE,
  FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE,
  FOREIGN KEY (repliedID) REFERENCES replies(replyID) ON DELETE CASCADE
)